### PR TITLE
Fix bug in get_F_values

### PR DESCRIPTION
**Pull request by FelixMay**
Hi @dmcglinn and @rueuntal ,
a user of mobr pointed me to a bug. Which is subtle but important. The permutation for the F tests was flawed. I hope I fixed it now. Sorry for not creating a new branch for this PR. I hope it still works, as the change is minor, but important

### CODE REVIEW

**Comment by dmcglinn** [comment]
Thanks @FelixMay! Can you provide a brief description of what the problem was and how this fixes it so that when I roll out the new version we can note it in the NEWS.md file. Thanks!

**Comment by dmcglinn** [comment]
I worked through the code line by line and I found that the first fix
```
-      div_dat <- mutate(div_dat, group = sample(group))
+      div_dat <- div_dat %>%
+         group_by(index, n_rare) %>%
+         mutate(group = sample(group))
```
fixed a key bug in which the groups were being randomized across two strata (the biodiversity index, and the level of rarefaction). The updated code appears to be doing what we want which is to randomize the variable `group` within each strata. 

The second change only restructures the white space - no actual change to code function. 
```
-   F_rand <- dplyr::bind_rows(replicate(n_perm, get_F_values(dat_samples, permute = T), simplify = F)) %>% ungroup()
+   F_rand <- dplyr::bind_rows(replicate(n_perm, get_F_values(dat_samples, permute = T), simplify = F)) %>% ungroup()
```
This looks good to merge. Thanks @FelixMay . It is kind of amazing how much `dplyr` has been incorporated into the boxplot code. I had hopes of refactoring the code to remove that dependency but that seems like a really big job and the `dplyr` is elegant. Nice job.

**Comment by FelixMay** [comment]
Hi @dmcglinn, thanks for merging. In your comment you perfectly describes what I did. So do you still need any infos from my side. Yes, I think `dplyr` helped a lot in `mobr_boxplots`, and will be hard to remove. However, as far as I know we get around the trouble with all the second-level dependencies once `mobr` is on CRAN.

**Comment by dmcglinn** [comment]
no info needed from you thanks @FelixMay!

**Pull request merged**
