### PR TITLE
Fix minor bugs in mobr_boxplots.R and add first vignette

### PR DESCRIPTION
**Pull request by FelixMay**
Here is a new try with a clean pull request #106.
I hope it works now.

### CODE REVIEW

**Comment by dmcglinn** [comment]
Everything looks pretty good except remove these files from the PR `scripts/mobr_example_sim_data.R` and and `mobr.Rproj`. It appears that `scripts/mobr_example_sim_data.R` was an old file that is now called `scripts/mobr_sensitivity.R`

**Comment by dmcglinn** [comment]
You'll have to use `git rm` and then commit the `removal` of those files and then push your changes

**Comment by FelixMay** [comment]
Alright, I deleted the files. Anything else required for merging?

**Comment by dmcglinn** [comment]
Looks great! Thanks merging.

**Pull request merged**
