### PR TITLE
Update mobr_boxplots.R

### PR DESCRIPTION
**Pull request by T-Engel**
I implemented the bias correction for the effective number of species in calc_PIE.

### CODE REVIEW

**Comment by dmcglinn** [comment]
Thanks @T-Engel just a few requests before this is ready to merge: 
* the mobr project is using 4 spaces for each level of nesting in functions and loop / if statements, please change your code accordingly to maintain consistent style (also it will make the diff cleaner and show exactly how you modified the functional rather than style components of the function 
* can you please add documentation to https://github.com/T-Engel/mobr/blob/020e692dc9391d980e9f1762d310707ed69b0e1e/R/mobr_boxplots.R#L51 and https://github.com/T-Engel/mobr/blob/020e692dc9391d980e9f1762d310707ed69b0e1e/R/mobr_boxplots.R#L407 that make it clear we are using a bias corrected version of `S_PIE`. 
* compile documentation using `devtools::document()`

Let me know if you have any questions or trouble with any of this. Thanks again for this important contribution. I will add you to the package coauthor list after merging.

**Comment by T-Engel** [comment]
Sure, I will add the spaces and change the documentation.
I'm not sure about the compilation part, though. I'm new to github and developing. I still use the browser interface to make the changes and I'm not sure how devtools works and where to use it...

**Comment by dmcglinn** [comment]
Hey @T-Engel I should have been clearer about the compilation part. When I wrote `devtools::document()` that was to indicate an R function called `document` in the package `devtools`. The `::` is just a short hand way to to get R to load a package on the fly without having to use `library(devtools)` it is useful when you only need one function from a package it also helps to clear up any ambiguity in the namespace. The function `document` looks above each function for the documentation. This is the text preceded by `#' `. Let me know if you still have questions. Also here is a good reference for building R packages and using git: http://r-pkgs.had.co.nz/

**Comment by T-Engel** [comment]
Hi @dmcglinn . I think I managed to update the documentation. Let me know if there is anything else that you need me to do or change.

**Comment by T-Engel** [comment]
Alright. Should be fine now. This has been good practice for me. Thanks!

**Comment by dmcglinn** [comment]
Great thank you so much again for this contribution!

**Comment by T-Engel** [comment]
Hi @dmcglinn,

We noticed that the changes I made are not active yet when we reinstall the package from github. Calc_PIE is still the old function. I'm not sure what the problem is but maybe you need to rebuild the package or something. Let me know if you need me to do anything.
See you soon in Leipzig!

**Comment by T-Engel** [comment]
Actually, never mind that, sorry! It is working. My mistake.

**Pull request merged**
