### PR TITLE
Analytical solution to rescaling between ind-based and nonspat curves.

### PR DESCRIPTION
**Pull request by rueuntal**
This is my attempt to write an analytical solution for the rescaling part in the N-comparison. The trick is to replace `lchoose()` with `lgamma()`, which accommodates non-integer inputs. 

Simple test scenarios for the new function `rescale_rarefaction()`:
```
# When ratio is 1, it works the same as rarefaction()
x = c(1, 2, 5, 7, 9)
effort = 1:sum(x)
rarefaction(x, 'indiv', effort)
rescale_rarefaction(x, 1, effort)

# When the ref_dens is two times group_dens (ratio = 2), the x-axis is rescaled accordingly
print(c(as.numeric(rarefaction(x, 'indiv', 2)), rescale_rarefaction(x, 2, 4)))
print(c(as.numeric(rarefaction(x, 'indiv', 5)), rescale_rarefaction(x, 2, 10)))
```

If this looks good, the dependency of `pracma` can be dropped.

### CODE REVIEW

**Comment by rueuntal** [comment]
Derivation below. Hopefully it's legible! 
img_20170123_182605

**Comment by dmcglinn** [comment]
wow! awesome! Let me test this out real quick.

**Comment by dmcglinn** [comment]
Based on my tests everything looks good! Great job! Really nice insight here.  It seems to me though that we may not want two rarefaction functions but just one. How do you feel about just modifying the rarefaction function directly so that it uses `lgamma` rather than `lchoose`. The default value of ratio would be 1 unless specified differently. The only real big argument against this I can see is if using `lgamma` is a slower than the `lchoose` approach but a little bit of testing suggests that is not true the `lgamma` approach actually appears slightly faster.

**Comment by rueuntal** [comment]
That would be great! I was thinking about that but decided against it only
because it would take a bit more time to code and I didn't want to break
the rarefaction function by mistake. If you feel like it, take it away!

**Comment by dmcglinn** [comment]
Cool will do I'm going to merge this PR and not merge #121 because your solution is better than mine!

**Comment by dmcglinn** [comment]
Additional testing suggests that as N gets large the `lgamma` approach is slightly slower than the traditional rarefaction approach but so far the difference is pretty small for example
```r
# for the morlay dataset which has 116,852 individuals
x = mor$comm
system.time(rarefaction(x, 'indiv'))
   user  system elapsed 
 11.155   0.080  11.242 
system.time( rescale_rarefaction(x, 1, 1:sum(x)))
   user  system elapsed 
 16.167   0.068  16.244 
```
for datasets with fewer individuals the difference is smaller.

**Comment by rueuntal** [comment]
thanks @dmcglinn . If the difference becomes a problem I guess we can implement an artificial switch point .

**Comment by dmcglinn** [comment]
it would make the code more complex but we could have a fall back to the traditional hypergeometric formulation when ratio is 1

**Comment by rueuntal** [comment]
sounds good if you like it. thanks for doing the testing!

**Comment by dmcglinn** [comment]
I'm looking at the ratio of run times averaging over 5 runs and it appears the gamma approach takes typically twice as long when N is relatively small and when N gets larger this drops to 1.5 times as long. So if we're running 1000 permutations then yea I guess maybe making the rescaled rarefaction approach becoming our default formulation may not be the best idea. We should send your analytical formulation to John Harte so he can give us an approximation ;P

**Comment by rueuntal** [comment]
noooo you know how I feel about approximation ;) since the ratio thing is only implemented in the effect of N, I'm hoping it would be faster than the interpolation (though that may not be true).

**Comment by dmcglinn** [comment]
Your note about the interpolation being potentially faster led me to do some checking and it actually turns out that it is a damn good thing you came up with the analytical because even my interpolation solution from #121 was behaving poorly when density of the treatment was greater than the average density in other words  `ratio` was less than 1. See the image below - the analytical is in red. I don't know what the heck the interpolation is doing but it doesn't do as bad when the ratio is close to 1. I guess I didn't explore it across a wide enough range of potential values. This is using the entire invasion dataset and artificially comparing it to a reference density this four times smaller than the treatment density. 

image

Also don't worry about the fact that the analytical curve terminates around 1200 individuals if the reference density was actually as small as I set it to be the scales it could sample across would be very small infact negative in this silly example.

**Comment by dmcglinn** [comment]
In the figure posted in the previous comment it is clear that the interpolated and analytical results are identical when sampling effort (i.e., number of individuals) across the small values of sampling effort which is where comparisons would actually be made which at least suggests that the interpolation method may be still somewhat viable but a side-by-side speed test of the analytical and the interpolated approaches for the invasion dataset suggests that the analytical approach is faster

```
# across 100 permutations just testing for N effect we get the following for interpolated speed
Computing null model for N effect
  |========================================| 100%
   user  system elapsed 
 30.894   0.027  30.889 
# and here is the speed for the analytical

Computing null model for N effect
  |========================================| 100%
   user  system elapsed 
 14.924   0.004  14.919 
```

These last time results I think are the nail in the coffin for any thoughts about the comparable utility of the interpolation approach.

**Comment by rueuntal** [comment]
Awesome. Thanks for carrying out all these robustness tests. I wouldn't
expect interpolation to misbehave either! Good that we can get rid of it
(and a dependency too).

**Pull request merged**
