### PR TITLE
First vignette draft

### PR DESCRIPTION
**Pull request by FelixMay**
Hi @rueuntal and @dmcglinn ,
I tried to fix some minor bugs in the mob_stats and boxplots functions, but the main thin is a first vignette draft. Please let me know extensions and changes we would like to have in the vignette.

### CODE REVIEW

**Comment by dmcglinn** [comment]
This looks like a great start @FelixMay! The only big problem I see with the PR is that you have included a merge from a different PR in it. This will unnecessarily make the commit history messy. Can you please remove f495fb1 from your PR? 

Also ideally it would be great if we could be consistent with our coding style. It seems you prefer `<-` while I prefer `=` for assigning objects. I think this is just a matter of taste or do you know of a stronger reason we should prefer `<-` in our code? @rueuntal doesn't have a preference.

Thanks!
Dan

**Comment by FelixMay** [comment]
Hi @dmcglinn, oh sorry for being messy. Well, obviously my experience with pull requests and merching branches and forks is still very limited. Could you sent me hints how to remove the f495fb1 from my pull request? Otherwise I could also consult a more experienced GitHub user here at iDiv.

With the coding style that is true. I think `<-` is more explicit that it is a definition and clearly different from condition checking `==`. But, I do not mind using `=` instead. You guys did much more of the coding, so I will adopt your style!

**Comment by dmcglinn** [comment]
Hey @FelixMay I think this page could help with removing the unwanted commit from the PR
http://stackoverflow.com/questions/36168839/how-to-remove-commits-from-pull-request

It looks like all you need possibly is
```
git checkout master
git revert f495fb1
git push origin master
```

**Comment by dmcglinn** [comment]
this still looks the same to me.

**Pull request closed without merging**
