### PR TITLE
Update boxplot stats 

### PR DESCRIPTION
**Pull request by dmcglinn**
The key changes are: 
1. adding observed value to the computation of the permutation based p-value (as recommended by Legendre and Legendre 1998). Also I followed the approach taken in `vegan` in which the machines relative floating point accuracy is subtracted from the observed so as to ensure rounding errors do not influence the p-value - this is a more conservative approach. 
2. minor updates to function documentation
3. I replaced sample-level with alpha-scale and group-level with gamma-scale in the documentation this is to bring the documentation inline with the manuscript. This change still needs to be added to the naming of objects in the code but that will be a pretty big job that will have to come later.

### CODE REVIEW

**Comment by dmcglinn** [comment]
@FelixMay @rueuntal and @ngotelli this is relatively minor but do you all agree with including the observed test statistic in the distribution of permuted test statistics when computing the p-value - if feel like we discussed this in the past but I cannot find an issue that referenced this point. If you guys agree with taking this approach then I can also update the p-value calculation for the continuous-scale analysis.

**Comment by rueuntal** [comment]
Hey @dmcglinn my recollection is also that we've discussed this in the past (though couldn't recall which issue it was either), and both I and @ngotelli objected to it, based on the ground that including the observed value changes the underlying frequency distribution by inflating the occurrence of itself. Imagine a case where there are 100 possible permutations, and we randomly take 100 samples (with replacement). If the observed value is not included, then each possible permutation would have an expected occurrence of 1. If the observed value is included, then that particular permutation would have an expected occurrence of 2, twice the probability as compared to other permutations.

It probably wouldn't make a huge difference in number one way or the other, but I find it to be conceptually unappealing.

**Comment by FelixMay** [comment]
Hi @dmcglinn, I do not have a good answer to the p-value question. When Legendre and Legendre 1998 say you should do it like this, it is tempting tin jsut follow their advice. But @rueuntal anc @ngotelli argument makes sense to me. Sorry, I cannot resolve this

**Comment by dmcglinn** [comment]
Thanks @rueuntal for rehashing this for me, and thanks @FelixMay for your input too. Here is Legendre and Legendre's 1998 justification:

>Add to these the reference value of the t statistic, computed for the unpermuted
vectors. Since H0 is being tested, this value is considered to be one that could be
obtained under H0 and, consequently, it should be added to the reference distribution
(Hope, 1968; Edgington, 1995; Manly, 1997). Together, the unpermuted and permuted
values form an estimate of the sampling distribution of t under H0, to be used in the
next step.

This makes the most sense to me and it is how others have approached this problem (see `vegan` and `spatstat` packages).  I cannot find any references for not including the observed statistic when carrying out H0 testing so I'm going to adopt our code to the Legendre approach.

**Pull request merged**
