### PR TITLE
Plot-level permutation tests

### PR DESCRIPTION
**Pull request by FelixMay**
Now I added the plot-level permutation tests

### CODE REVIEW

**Comment by dmcglinn** [comment]
I think that we do not want to strip out the plots with no individuals from the analysis. If you sample a plot and you don't encounter any individuals that is actually very relevant information (much more so than if you had not sampled that site which is how your patch would treat it). I assume you instituted this drop to prevent warnings / errors from downstream statistics - is that correct? Or was there a different reason?

**Comment by dmcglinn** [comment]
The permutation tests look good thanks for those!

**Comment by FelixMay** [comment]
Hi @dmcglinn, a sorry. Of course you are absolutely right that zero individuals is an important information. Then I will remove this commit from my pull request.  However, a plot with zero individuals leads to rarefied richness = 0 and ENS_PIE = infinity. I wonder how to deal with that for the boxplots? Just remove the plots for these two indices and throw a warning? Any other ideas?

**Comment by dmcglinn** [comment]
Great question. Brian McGill had these suggestions as potential options to consider

> a) use the 10th percentile of N, rounding up so that we never use the minimum N (or maybe 20th percentile?)
b) set a minimum threshold e.g. 10 so rarefy to N=max(10,min(N_i)) where i varies across the plots
c) use a combination of a & b (e.g. N=max(10,10th percentile N_i)
d) do a,b, or c in an asymmetric way (i.e. only use N_i from the treatment plots
This would mean plots with N<cutoff would have to be thrown out of the box plots.> 

This is pretty subjective but I like option (b) where we set a hard cut off of 10, samples without at least 10 individuals won't be included in the boxplot statistics but also will not be removed from the analysis completely (i.e., they will still be members of the `mob_in` object). @rueuntal and @ngotelli what do you guys think?

**Comment by ngotelli** [comment]
I also favor option b, and in fact even added some new text advocating a "rule of 10" (from my stats primer) for having a minimum of 10 observations for each treatment group or covariate that is added a sampling design.

**Comment by rueuntal** [comment]
@dmcglinn - thanks for explaining this. I'd lean towards (b) too because the check will then only comes into effect when some plots have low abundances. Another question is do we want to removed these plots from all comparisons of the boxplots, or just S_rarefy (which I think we've decided not to include) and PIE?

**Comment by dmcglinn** [comment]
Thanks it sounds like (b) is the consensus. I guess I would favor only using the 10 individual cutoff for rarefied S and ENS_PIE (I think it may be relevant for S_chao too b/c extrapolated richness of zero seems strange)?

**Comment by rueuntal** [comment]
It now gets me to think a bit. I'd definitely be more comfortable keeping the plots for S & N (Dan I think this is what you are saying as well?), because zero or low abundance/richness is still meaningful information to illustrate what's changed between treatments. Not including them for S_rarefy also makes sense, because it would then force all other plots to lose information by rarefying them down. But since now we are not including S_rarefy in the boxplots, should me just throw all plots in there (maybe except for the zero-abundance case scenario which messes up PIE and maybe S_chao)? If one plot has S_chao = 2, for example, that's still meaningful, right?

**Comment by ngotelli** [comment]
For the boxplots, it is critical to retain all plot data for abundance and species density because small numbers (and even zeroes) are important at that stage.

**Comment by rueuntal** [comment]
@dmcglinn @ngotelli @FelixMay how do you feel about throwing out zero-abundance plots for PIE (which yields Inf) but retain them for all other metrics (S, N, Schao)?

**Comment by dmcglinn** [comment]
I think that sounds good! @FelixMay can you code that up for us?

**Comment by ngotelli** [comment]
That works for me. As we have been emphasizing, the simple box plots are tied to a specific spatial scale, so we are always going to run into the issue for S(rarefied). Note also that PIE shows almost no sample-size dependency, so we really don't need to toss out small samples for that variable.

**Comment by FelixMay** [comment]
Hi mob team,
thanks for all the input. Yes, I can code this stuff easily. I will add the N for rarefied richness as an option (with default = 10) to mob_stats.

**Comment by FelixMay** [comment]
Hi @dmcglinn and @rueuntal,
I removed my inappropriate changes from `make_mob_in` and implemented the threshold for S_rare. Does the merge work?

Happy mobring ...

**Comment by dmcglinn** [comment]
Thanks @FelixMay this looks really good. Merging now.

**Pull request merged**
