### PR TITLE
Comestic changes to the plotting functions.

### PR DESCRIPTION
**Pull request by rueuntal**
Hey @dmcglinn - My feeling is that there's not much that we can do to reduce the bulkiness of the plotting function. You already did a great job getting the part organized, and it's still long because it's complicated :) So what I did here is purely cosmetic:
 - Change font size in `plot_rarefy` to be consistent with the rest
 - Replace delta with symbol
 - Change the y-axis in the third row as we discussed today

### CODE REVIEW

**Comment by dmcglinn** [comment]
These changes look great thanks @rueuntal . With the axis labels I have a slight preference for an axis label name like: "delta S (effect of SAD)" or "change in S due to SAD". The reason is that I think folks will have a hard time putting into words what they are seeing in the final 3 panels. For example if the curve is positive for "SAD effect" it is not immediately clear to the naive use that this means richness is higher due to either increased evenness or larger species pool. 

Also we should consider changing how the argument `display` is specified currently it accepts either 'rarefaction', 'delta S', or 'd-delta S'. If we think that d-delta S is confusing then we should change the name here. Nothing good is coming to mind at this late hour though. If we can't think of anything then we can just put that on the todo list and go ahead with these changes.

**Comment by rueuntal** [comment]
Good call! I'll see if I can come up with anything, if not today then definitely early tomorrow. 

That reminds me, I find the document for `pars_arg` a bit vague. Is there a better way to explain what it is? It might also be helpful if it shows up in one example.

**Comment by rueuntal** [comment]
I changed `d-delta S` to `partitioned change in S`. Feel free to change it if that still doesn't sound good.

**Comment by dmcglinn** [comment]
Thanks for the additional changes. I think the axis labels are better. I'm going to merge this change and then I will change the `diplay` argument back to `ddelta-S` because I think your alternative is too long, I can't think of anything better, and throughout the code in other functions that component is listed as `ddeltaS` so at least it will be consistent.

**Pull request merged**
